"""
publish.py — STEP 7: ship the trained model into Volee's database.

Run it:  python -m volee_ml.publish > model.sql      (then apply model.sql to Volee)

Volee runs this model in SHADOW MODE: every accepted singles challenge gets a
forecast written to a hidden table, and the real result is filled in when
the match is reported. Nobody sees it and it doesn't affect matchmaking. It
exists so the model can be measured on real club matches before anyone
decides whether to show it. (Volee's side: the migration
`2026_09_25_ml_shadow_forecasts.sql` in the Volee repo.)

The database can run logistic regression with no Python because, once
trained, the model is just numbers: a mean and spread per feature (for
scaling), a weight per feature, and an intercept. This script prints them as
one SQL statement that adds a new row to Volee's `ml_models` table and makes
it the active model. The previous version stays, so every stored forecast
can always say which model made it.

It also carries the tuned margin-aware Glicko settings (tune.py), which the
database uses to keep a shadow margin-aware rating for every player.
"""

from __future__ import annotations

import hashlib
import json
import sys
from dataclasses import asdict

import joblib

from volee_ml import config
from volee_ml.export import model_payload
from volee_ml.tune import load_tuned


def model_sql() -> str:
    model = joblib.load(config.MODELS_DIR / "logistic_regression.joblib")
    payload = model_payload(model)
    payload["margin_settings"] = asdict(load_tuned()["margin_glicko"])
    body = json.dumps(payload, separators=(",", ":"), sort_keys=True)
    version = "lr-" + hashlib.sha256(body.encode()).hexdigest()[:10]
    literal = body.replace("'", "''")
    return (
        "-- Generated by `python -m volee_ml.publish` (Volee-ML). Do not edit by hand.\n"
        "begin;\n"
        "update public.ml_models set active = false where active;\n"
        "insert into public.ml_models (version, spec, active, notes)\n"
        f"values ('{version}', '{literal}'::jsonb, true,\n"
        "        'Logistic regression trained on 2000-2019 ATP/WTA best-of-3 matches; "
        "test log loss 1.74% better than Volee Glicko-2 on 2023-26.')\n"
        "on conflict (version) do update set active = true;\n"
        "commit;\n"
    )


if __name__ == "__main__":
    sys.stdout.write(model_sql())
